In [3]:
import numpy as np

In [ ]:
#массив, как преобразовать его

In [4]:
my_list = [1,2,3,4,5,6,7,8]

In [5]:
my_array = np.array(my_list)

In [7]:
type(my_array)
my_array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
my_array * 10

array([10, 20, 30, 40, 50, 60, 70, 80])

In [10]:
my_tuple = (1,2,5,6,7,9)

In [11]:
np.array(my_tuple)

array([1, 2, 5, 6, 7, 9])

In [16]:
###создание массива

In [13]:
np.arange(10) # создает массив , 10 включена не будет

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(1,100,2) # от одного до ста с шагом == 2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [ ]:
#linspace
numpy.linspace() - это функция библиотеки NumPy, которая создает одномерный массив чисел (линейную последовательность) 
в заданном диапазоне с равномерным распределением значений.
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

start: Начальное значение последовательности.
stop: Конечное значение последовательности.
num: Количество чисел для генерации (по умолчанию 50).
endpoint: Булевое значение, указывающее, следует ли включать stop в выходной массив (по умолчанию True).
retstep: Если True, функция вернет шаг между значениями (по умолчанию False).
dtype: Тип данных для выходного массива (если не указан, будет определен автоматически).
axis: Ось, по которой будет создаваться массив (по умолчанию 0).

In [18]:
np.linspace(0, 30, 11)

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30.])

In [21]:
np.linspace(0, 30, 11, retstep=True) #в конце вывордит шаг, через какое числа расставлены

(array([ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30.]), 3.0)

In [ ]:
#узнать количество элементов

In [ ]:
np.linspace(0, 30, 11).size

In [ ]:
#zeros()

In [22]:
np.zeros(10) #массив из десяти элементов '0'

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#ones()

In [23]:
np.ones(10) #массив из десяти элементов '1'

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.zeros((10,5)) # создает 10 строк и 5 колонок

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.zeros(11, dtype='str') #массив заполняется пустыми строками

array(['', '', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [ ]:
#векторы

In [33]:
ave_array = np.arange(35)
ave_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34])

In [ ]:
#обращаемся по индексу

In [34]:
ave_array[1]

1

In [39]:
ave_array.shape = (7, 5)  # если мы просто прописываем ave_array.shape, то мы узнаем размер , 
#а если мы еще ставим = то можем сами выбрать как будет выглядеть 
ave_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [40]:
ave_array[1] #уже выводит строку

array([5, 6, 7, 8, 9])

In [42]:
ave_array[5, 3] #ave_array[строка, столбец]

28

In [46]:
zero_mod_2_mask = 0 == (ave_array % 2)
'''ave_array % 2: Вычисляет остаток от деления каждого элемента массива ave_array на 2. 
Это дает нам массив, в котором каждый элемент равен остатку от деления соответствующего элемента массива ave_array на 2.
0 == (ave_array % 2): Сравнивает каждый элемент полученного массива с 0. Если остаток от деления элемента на 2 равен 0, т
о это значит, что элемент четный, и условие вернет True, в противном случае - False. Таким образом, мы создаем булев массив, 
где True соответствует четным элементам массива ave_array, а False - нечетным.'''
zero_mod_2_mask

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [48]:
'''так можно играться, например :'''
zero_mod_mask = 10 < (ave_array) #то есть в правой части мы прописываем условие, и оно уже потом выводит 
#true или false для каждого значения
zero_mod_mask

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [58]:
zero_mod_mask1 = 0 == (ave_array % 2)
zero_mod_mask1

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [56]:
sub_array = ave_array[zero_mod_mask] # здесь по факту мы накладываем условие, обынчая булевая маска
sub_array.shape = (6,4)
sub_array

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26],
       [27, 28, 29, 30],
       [31, 32, 33, 34]])

In [57]:
sub_array[sub_array > 25] # еще одна булевая маска

array([26, 27, 28, 29, 30, 31, 32, 33, 34])

In [ ]:
# мы можем объединять условия при помощи np.logical_and()

In [60]:
comb_mask = np.logical_and(zero_mod_mask1, zero_mod_mask)
comb_mask # здесь показываются булевое значение элементов которые делятся и на 2 без остатка и которые больше 10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [61]:
ave_array[comb_mask] # а вот здесь уже показываются значения, которые были отфильтрованы о булевой маске

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34])

In [ ]:
#broadcasting

In [64]:
ave_3D_array = np.arange(70)
ave_3D_array.shape = (2,7,5)
ave_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [66]:
5 * ave_3D_array - 10

array([[[-10,  -5,   0,   5,  10],
        [ 15,  20,  25,  30,  35],
        [ 40,  45,  50,  55,  60],
        [ 65,  70,  75,  80,  85],
        [ 90,  95, 100, 105, 110],
        [115, 120, 125, 130, 135],
        [140, 145, 150, 155, 160]],

       [[165, 170, 175, 180, 185],
        [190, 195, 200, 205, 210],
        [215, 220, 225, 230, 235],
        [240, 245, 250, 255, 260],
        [265, 270, 275, 280, 285],
        [290, 295, 300, 305, 310],
        [315, 320, 325, 330, 335]]])

In [ ]:
#dot product

In [72]:
left_mat = np.arange(6).reshape(2,3)
right_mat = np.arange(15).reshape(3,5)
dot_product = np.dot(left_mat, right_mat)

In [73]:
dot_product

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

In [77]:
ave_3D_array.sum(axis = 1) # сумма по элементам столбцов

array([[105, 112, 119, 126, 133],
       [350, 357, 364, 371, 378]])

In [79]:
ave_3D_array.sum(axis = 2) # складываются значения по строкам

array([[ 10,  35,  60,  85, 110, 135, 160],
       [185, 210, 235, 260, 285, 310, 335]])

In [ ]:
# broadcasting rules

In [81]:
ave_2D_array = np.ones(35, dtype='int_').reshape((7,5)) * 5
ave_2D_array

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [84]:
ave_random_2D_array = np.random.random((7,5))
ave_random_2D_array

array([[0.97778573, 0.06254696, 0.80118377, 0.97707959, 0.11566084],
       [0.32366294, 0.92689359, 0.98710837, 0.10110296, 0.16813491],
       [0.75766533, 0.57730746, 0.95974566, 0.32580553, 0.30198101],
       [0.49356909, 0.26804769, 0.73720181, 0.12561413, 0.55697981],
       [0.88959047, 0.63298851, 0.05301285, 0.38087412, 0.83607684],
       [0.61580532, 0.69523647, 0.84990834, 0.6368943 , 0.8485708 ],
       [0.8837828 , 0.8791242 , 0.42327942, 0.18361679, 0.0121311 ]])

In [86]:
np.set_printoptions(precision=4)
ave_3D_array * ave_random_2D_array

array([[[ 0.    ,  0.0625,  1.6024,  2.9312,  0.4626],
        [ 1.6183,  5.5614,  6.9098,  0.8088,  1.5132],
        [ 7.5767,  6.3504, 11.5169,  4.2355,  4.2277],
        [ 7.4035,  4.2888, 12.5324,  2.2611, 10.5826],
        [17.7918, 13.2928,  1.1663,  8.7601, 20.0658],
        [15.3951, 18.0761, 22.9475, 17.833 , 24.6086],
        [26.5135, 27.2529, 13.5449,  6.0594,  0.4125]],

       [[34.2225,  2.2517, 29.6438, 37.129 ,  4.5108],
        [12.9465, 38.0026, 41.4586,  4.3474,  7.3979],
        [34.0949, 26.5561, 45.108 , 15.6387, 14.7971],
        [24.6785, 13.6704, 38.3345,  6.6575, 30.0769],
        [48.9275, 35.4474,  3.0217, 22.0907, 49.3285],
        [36.9483, 42.4094, 52.6943, 40.1243, 54.3085],
        [57.4459, 58.0222, 28.3597, 12.4859,  0.837 ]]])

In [ ]:
# структурированные массивы

In [97]:
employee_data_def = [('name', 'S6'), ('height', 'f8'), ('weight', 'f8'), ('age', 'i8')]
employee_data_def

[('name', 'S6'), ('height', 'f8'), ('weight', 'f8'), ('age', 'i8')]

In [98]:
employees_array=np.zeros((4), dtype = employee_data_def)
employees_array

array([(b'', 0., 0., 0), (b'', 0., 0., 0), (b'', 0., 0., 0),
       (b'', 0., 0., 0)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [99]:
employees_array[3] = ('Vova', 186, 81, 19)
employees_array

array([(b'',   0.,  0.,  0), (b'',   0.,  0.,  0), (b'',   0.,  0.,  0),
       (b'Vova', 186., 81., 19)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [102]:
company_employees = np.zeros((4,3,2), dtype=employee_data_def)
company_employees

array([[[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]]],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [104]:
company_employees[3,2,1] = ('Vova', 186, 81, 19)  # слой, строка, колонка
company_employees

array([[[(b'',   0.,  0.,  0), (b'',   0.,  0.,  0)],
        [(b'',   0.,  0.,  0), (b'',   0.,  0.,  0)],
        [(b'',   0.,  0.,  0), (b'',   0.,  0.,  0)]],

       [[(b'',   0.,  0.,  0), (b'',   0.,  0.,  0)],
        [(b'',   0.,  0.,  0), (b'',   0.,  0.,  0)],
        [(b'',   0.,  0.,  0), (b'',   0.,  0.,  0)]],

       [[(b'',   0.,  0.,  0), (b'',   0.,  0.,  0)],
        [(b'',   0.,  0.,  0), (b'',   0.,  0.,  0)],
        [(b'',   0.,  0.,  0), (b'',   0.,  0.,  0)]],

       [[(b'',   0.,  0.,  0), (b'',   0.,  0.,  0)],
        [(b'',   0.,  0.,  0), (b'',   0.,  0.,  0)],
        [(b'',   0.,  0.,  0), (b'Vova', 186., 81., 19)]]],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [106]:
company_employees['height']

array([[[  0.,   0.],
        [  0.,   0.],
        [  0.,   0.]],

       [[  0.,   0.],
        [  0.,   0.],
        [  0.,   0.]],

       [[  0.,   0.],
        [  0.,   0.],
        [  0.,   0.]],

       [[  0.,   0.],
        [  0.,   0.],
        [  0., 186.]]])

In [ ]:
#добавление элементов в массив

In [108]:
av_array = (np.arange(24).reshape(2,3,4))
av_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [119]:
trial_array = np.append(av_array, [5,6,7,8,9,10,11,12])
trial_array.reshape(2,4,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [122]:
new_trial = np.array(np.arange(24).reshape(2,3,4)*10+5)
new_trial

array([[[  5,  15,  25,  35],
        [ 45,  55,  65,  75],
        [ 85,  95, 105, 115]],

       [[125, 135, 145, 155],
        [165, 175, 185, 195],
        [205, 215, 225, 235]]])

In [131]:
np.append(av_array,new_trial, axis = 0 ) # можно игратьс] с осями

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[  5,  15,  25,  35],
        [ 45,  55,  65,  75],
        [ 85,  95, 105, 115]],

       [[125, 135, 145, 155],
        [165, 175, 185, 195],
        [205, 215, 225, 235]]])

In [132]:
np.append(av_array,new_trial, axis = 1 )

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  5,  15,  25,  35],
        [ 45,  55,  65,  75],
        [ 85,  95, 105, 115]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [125, 135, 145, 155],
        [165, 175, 185, 195],
        [205, 215, 225, 235]]])

In [ ]:
# stack

In [134]:
ave_stack = np.hstack((av_array,new_trial))
ave_stack

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  5,  15,  25,  35],
        [ 45,  55,  65,  75],
        [ 85,  95, 105, 115]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [125, 135, 145, 155],
        [165, 175, 185, 195],
        [205, 215, 225, 235]]])

In [151]:
r1 = np.array(np.arange(24).reshape(6,4))
r1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [152]:
r2 = np.array(np.arange(24, 48).reshape(6,4))
r2

array([[24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47]])

In [155]:
s = np.append(r1,r2, axis = 1)
s.shape

(6, 8)

In [156]:
s = np.append(r1,r2, axis = 0)
s.shape

(12, 4)

In [ ]:
# how to insert

In [163]:
av_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [166]:
insert_av_array = np.insert(av_array, 1, 666, axis=0)
insert_av_array

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[666, 666, 666, 666],
        [666, 666, 666, 666],
        [666, 666, 666, 666]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

In [167]:
insert_av_array = np.insert(av_array, 1, 666, axis=1)
insert_av_array

array([[[  0,   1,   2,   3],
        [666, 666, 666, 666],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [666, 666, 666, 666],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

In [168]:
insert_av_array = np.insert(av_array, 1, 666, axis=2)
insert_av_array

array([[[  0, 666,   1,   2,   3],
        [  4, 666,   5,   6,   7],
        [  8, 666,   9,  10,  11]],

       [[ 12, 666,  13,  14,  15],
        [ 16, 666,  17,  18,  19],
        [ 20, 666,  21,  22,  23]]])

In [172]:
del_array = np.empty(av_array.shape) # создаем такой же по размеру как и av_array
del_array

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [175]:
np.copyto(del_array, av_array)
del_array

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]],

       [[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]])

In [179]:
np.delete(del_array, 1, axis=2)

array([[[ 0.,  2.,  3.],
        [ 4.,  6.,  7.],
        [ 8., 10., 11.]],

       [[12., 14., 15.],
        [16., 18., 19.],
        [20., 22., 23.]]])

In [ ]:
# конкатинация

In [184]:
alhpa = np.array([[1,2], [3,4]])
beta = np.array([[5,6]])

In [182]:
alhpa

array([[1, 2],
       [3, 4]])

In [185]:
beta

array([[5, 6]])

In [192]:
together = np.concatenate((alhpa,beta), axis = 0 )
together

array([[1, 2],
       [3, 4],
       [5, 6]])

In [203]:
together[1,1] = 666
together

array([[  1,   2],
       [  3, 666],
       [  5,   6]])

In [219]:
arrays = np.zeros((5,3,4))
for n in range(5):
    arrays[n] = np.random.random()
arrays

array([[[0.4677, 0.4677, 0.4677, 0.4677],
        [0.4677, 0.4677, 0.4677, 0.4677],
        [0.4677, 0.4677, 0.4677, 0.4677]],

       [[0.3702, 0.3702, 0.3702, 0.3702],
        [0.3702, 0.3702, 0.3702, 0.3702],
        [0.3702, 0.3702, 0.3702, 0.3702]],

       [[0.2656, 0.2656, 0.2656, 0.2656],
        [0.2656, 0.2656, 0.2656, 0.2656],
        [0.2656, 0.2656, 0.2656, 0.2656]],

       [[0.675 , 0.675 , 0.675 , 0.675 ],
        [0.675 , 0.675 , 0.675 , 0.675 ],
        [0.675 , 0.675 , 0.675 , 0.675 ]],

       [[0.3978, 0.3978, 0.3978, 0.3978],
        [0.3978, 0.3978, 0.3978, 0.3978],
        [0.3978, 0.3978, 0.3978, 0.3978]]])

In [ ]:
# stack

In [229]:
stack0 = np.stack(arrays, axis=0)
stack1 = np.stack(arrays, axis=1)
stack2 = np.stack(arrays, axis=2)

In [226]:
stack1

array([[[0.4677, 0.4677, 0.4677, 0.4677],
        [0.3702, 0.3702, 0.3702, 0.3702],
        [0.2656, 0.2656, 0.2656, 0.2656],
        [0.675 , 0.675 , 0.675 , 0.675 ],
        [0.3978, 0.3978, 0.3978, 0.3978]],

       [[0.4677, 0.4677, 0.4677, 0.4677],
        [0.3702, 0.3702, 0.3702, 0.3702],
        [0.2656, 0.2656, 0.2656, 0.2656],
        [0.675 , 0.675 , 0.675 , 0.675 ],
        [0.3978, 0.3978, 0.3978, 0.3978]],

       [[0.4677, 0.4677, 0.4677, 0.4677],
        [0.3702, 0.3702, 0.3702, 0.3702],
        [0.2656, 0.2656, 0.2656, 0.2656],
        [0.675 , 0.675 , 0.675 , 0.675 ],
        [0.3978, 0.3978, 0.3978, 0.3978]]])

In [227]:
stack2

array([[[0.4677, 0.3702, 0.2656, 0.675 , 0.3978],
        [0.4677, 0.3702, 0.2656, 0.675 , 0.3978],
        [0.4677, 0.3702, 0.2656, 0.675 , 0.3978],
        [0.4677, 0.3702, 0.2656, 0.675 , 0.3978]],

       [[0.4677, 0.3702, 0.2656, 0.675 , 0.3978],
        [0.4677, 0.3702, 0.2656, 0.675 , 0.3978],
        [0.4677, 0.3702, 0.2656, 0.675 , 0.3978],
        [0.4677, 0.3702, 0.2656, 0.675 , 0.3978]],

       [[0.4677, 0.3702, 0.2656, 0.675 , 0.3978],
        [0.4677, 0.3702, 0.2656, 0.675 , 0.3978],
        [0.4677, 0.3702, 0.2656, 0.675 , 0.3978],
        [0.4677, 0.3702, 0.2656, 0.675 , 0.3978]]])

In [ ]:
#split

In [230]:
before_split = stack0
before_split 

array([[[0.4677, 0.4677, 0.4677, 0.4677],
        [0.4677, 0.4677, 0.4677, 0.4677],
        [0.4677, 0.4677, 0.4677, 0.4677]],

       [[0.3702, 0.3702, 0.3702, 0.3702],
        [0.3702, 0.3702, 0.3702, 0.3702],
        [0.3702, 0.3702, 0.3702, 0.3702]],

       [[0.2656, 0.2656, 0.2656, 0.2656],
        [0.2656, 0.2656, 0.2656, 0.2656],
        [0.2656, 0.2656, 0.2656, 0.2656]],

       [[0.675 , 0.675 , 0.675 , 0.675 ],
        [0.675 , 0.675 , 0.675 , 0.675 ],
        [0.675 , 0.675 , 0.675 , 0.675 ]],

       [[0.3978, 0.3978, 0.3978, 0.3978],
        [0.3978, 0.3978, 0.3978, 0.3978],
        [0.3978, 0.3978, 0.3978, 0.3978]]])

In [237]:
s0 = np.split(before_split, 5, axis = 0)
s0

[array([[[0.4677, 0.4677, 0.4677, 0.4677],
         [0.4677, 0.4677, 0.4677, 0.4677],
         [0.4677, 0.4677, 0.4677, 0.4677]]]),
 array([[[0.3702, 0.3702, 0.3702, 0.3702],
         [0.3702, 0.3702, 0.3702, 0.3702],
         [0.3702, 0.3702, 0.3702, 0.3702]]]),
 array([[[0.2656, 0.2656, 0.2656, 0.2656],
         [0.2656, 0.2656, 0.2656, 0.2656],
         [0.2656, 0.2656, 0.2656, 0.2656]]]),
 array([[[0.675, 0.675, 0.675, 0.675],
         [0.675, 0.675, 0.675, 0.675],
         [0.675, 0.675, 0.675, 0.675]]]),
 array([[[0.3978, 0.3978, 0.3978, 0.3978],
         [0.3978, 0.3978, 0.3978, 0.3978],
         [0.3978, 0.3978, 0.3978, 0.3978]]])]

In [ ]:
# fliplr

In [244]:
m = np.array(np.arange(24).reshape(6,4))

In [250]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [247]:
np.fliplr(m)

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12],
       [19, 18, 17, 16],
       [23, 22, 21, 20]])

In [252]:
m = np.array(np.arange(24).reshape(4,2,3))
m

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [254]:
np.flipud(m)

array([[[18, 19, 20],
        [21, 22, 23]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[ 0,  1,  2],
        [ 3,  4,  5]]])

In [ ]:
# roll

In [260]:
ar = np.array(np.arange(30))
np.roll(ar, 4) # проиходит сдвиг на четыре

array([26, 27, 28, 29,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
       13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [ ]:
# tile

In [261]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [266]:
np.tile(ar, (4, 3)) # просто повторяет массив и загоняет его в новый массив

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,  0,  1,
         2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,  0,  1,  2,  3,
         4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
        20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,  0,  1,
         2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,  0,  1,  2,  3,
         4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
        20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,  0,  1,
         2,  3,  4,  5,  6,  7,  8,  9

In [267]:
np.tile(ar, 4) # просто повторяет массив и загоняет его в новый массив

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,  0,  1,  2,  3,
        4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
       12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29])